#!/bin/bash

REMOTE_USER="root"
#USER='vlad'  # env var $USER exist by default
REMOTE_ADDRESS="188.42.128.188"
PROJECT_NAME="eos-$USER"
DEPLOY_PATH="/8TB4/projects/"
LOCAL_PROJECT_PATH=.   # just run from project directory
DEPLOY_FULL_PATH="$REMOTE_USER@$REMOTE_ADDRESS:$DEPLOY_PATH$PROJECT_NAME"

NOTEBOOKS_DIR="$LOCAL_PROJECT_PATH/notebooks"
RESOURCES_DIR="$LOCAL_PROJECT_PATH/resources"
SCRIPTS_DIR="$LOCAL_PROJECT_PATH/src"

NOTEBOOKS_REMOTE_DIR="$DEPLOY_FULL_PATH/notebooks"
RESOURCES_REMOTE_DIR="$DEPLOY_FULL_PATH/resources"
SCRIPTS_REMOTE_DIR="$DEPLOY_FULL_PATH/src"
